### ISSUE TITLE
不用大驼峰，差评

### ISSUE THREAD

**Issue by nc7s** [messense/optionaldict#1]

**Comment by messense** [comment]
不是还有个别名 OptionalDict 么。再说了 collections.defaultdict 也没用驼峰……

发自我的 iPhone

**Comment by idf** [comment]
pseudo-namespaces 标准是用all lower case吧？

**Comment by nc7s** [comment]
@messense 没看见，文档里是 `optionaldict()`
@idf 说的是类名不是包

**Comment by messense** [comment]
@zorceta 更新了 README..........

**Comment by nc7s** [comment]
[PEP 8 > Naming Conventions > Prescriptive: Naming Conventions > Class Names](https://www.python.org/dev/peps/pep-0008/#class-names)

> Class names should normally use the CapWords convention.
> The naming convention for functions may be used instead in cases where the interface is documented and used primarily as a callable.

啊所以说你大概是对的 @messense

**Comment by idf** [comment]
@zorceta lowercase class name for pseudo-namesapces吧？`class socket` in https://hg.python.org/releasing/3.5/file/5b845fec4daf/Lib/socket.py
